export const baseUrl = `${process.env.NEXTAUTH_URL}/api/`;
export const environment = {
    socketUrl: process.env.NEXT_PUBLIC_SOCKET,
    baseUrl: baseUrl,
    authUrl: baseUrl + 'auth/',
    categoriesUrl: baseUrl + 'admin/categories',
    countries: baseUrl + 'countries',
    regions: baseUrl + 'regions',
    allRegions: baseUrl + 'all-regions',
    countryRegions: baseUrl + 'country-regions',
    languages: baseUrl + 'admin/language_list',
    addNewLanguage: baseUrl + 'admin/add-language',
    updateLanguage: baseUrl + 'admin/update_language',
    documentTypes: baseUrl + 'admin/document_types',
    createDocumentType: baseUrl + 'admin/document_type',
    users: baseUrl + 'admin/user_list',
    updateUser: baseUrl + 'admin/update_user',
    imageUrl: `${process.env.NEXTAUTH_URL}/`,
    setDefaultLanguage: baseUrl + 'admin/set_default_language',
    saveDocumentTypes: baseUrl + 'admin/add_document_types',
    currenciesUrl: baseUrl + 'admin/currencies',
    updateDocumentType: baseUrl + 'admin/update_document_type',
    organizations: baseUrl + 'admin/organizations',
    emailTemplateList: baseUrl + 'admin/email-templates',
    bookingsList: baseUrl + 'admin/get-bookings',
    bookingDetails: baseUrl + 'admin/get-booking',
    bookingsExport: baseUrl + 'admin/bookings/export',
    addCategory: baseUrl + 'admin/add_category',
    updateSupplier: baseUrl + 'admin/update_supplier',
    userDetails: baseUrl + 'admin/user-info',
    saveOrganization: baseUrl + 'admin/organization/',
    organizationTranslations: baseUrl + 'admin/org_translation/',
    categoryTranslation: baseUrl + 'admin/category',
    updateCategory: baseUrl + 'admin/update_category',
    getDisputeTypes: baseUrl + 'admin/dispute_types',
    disputeType: baseUrl + 'admin/dispute_type',
    getNotifications: baseUrl + 'admin/notifications',
    getBookingDisputes: baseUrl + 'admin/booking-disputes',
    bookingDispute: baseUrl + 'admin/booking_dispute',
    verifyEmail: 'verify-email',
    dashboardStats: baseUrl + 'admin/dashboard/stats',
    countriesList: baseUrl + 'admin/countries',
    addCountry: baseUrl + 'admin/add_country',
    addTranslation: baseUrl + 'admin/country',
    getNationalities: baseUrl + 'admin/nationalities',
    addNationality: baseUrl + 'admin/add_nationality',
    addNationalityTranslation: baseUrl + 'admin/nationality',
    updateCountry: baseUrl + 'admin/update_country',
    updateNationality: baseUrl + 'admin/update_nationality',
    commonSettings: baseUrl + 'admin/settings',
    updateCommonSetting: baseUrl + 'admin/setting',
    supplierStripeDetail: baseUrl + 'admin/supplier_stripe',
    supplierAdditionalExpenses: baseUrl + 'admin/additional-expenses',
    measurements: baseUrl + 'admin/measurements',
    createMeasurement: baseUrl + 'admin/measurement',
    getRegions: baseUrl + 'admin/regions',
    region: baseUrl + 'admin/region',
    chatList: baseUrl + 'admin/chats',
    chatUploadFile: baseUrl + 'chat/upload-file',
    sendChatMessage: baseUrl + 'admin/send-message',
    joinChat: baseUrl + 'admin/join-conversation',
    disputeAction: baseUrl + 'admin/dispute_action',
    updateAdminProfile: baseUrl + 'admin/update_profile',
    userAdminProfile: baseUrl + 'auth/profile',
    userAnalyticsData: baseUrl + 'admin/user_analytics',
    bookingAnalyticsData: baseUrl + 'admin/booking_analytics',
    transactionAnalyticsData: baseUrl + 'admin/transaction_analytics',
    getTransactions: baseUrl + 'admin/get-transactions',
    getAppUrls: baseUrl + 'get-app-urls',
    getBookingTransactions: baseUrl + 'admin/get-booking-transactions',
    getBookingTransactionsSummary: baseUrl + 'admin/get-booking-transactions/summary',
    getBookingTransactionsExport: baseUrl + 'admin/get-booking-transactions/export',
    uploadExcel: baseUrl + 'admin/upload-excel',
    approvedUsers: baseUrl + 'admin/pre-approved-users', 
    addApprovedUser: baseUrl + 'admin/add-approved',
    approvedUserDetails: baseUrl + 'admin/approved-user-info',
    updateApprovedUser: baseUrl + 'admin/update-approved',
    allUsersList: baseUrl + 'admin/all-users',
    updateApprovedDuration: baseUrl + 'admin/update-approved-duration',
    referralSettings: baseUrl + 'admin/referral-settings',
    addReferralSetting: baseUrl + 'admin/add-referral-setting',
    updateReferralSetting: baseUrl + 'admin/update-referral-setting',
    getReferralBonus: baseUrl + 'referral/all-referrals',
    allCountryUserList: baseUrl + 'admin/all-country-users',
    allCountryOrganizationList: baseUrl + 'admin/country-organizations',
    updateReferralPoints: baseUrl + 'referral/update-points',
    updateSubscriptionOptions: baseUrl + 'admin/update-subscription-options',
    inactiveItems: baseUrl + 'admin/inactive_items',
    // Broadcast — audience catalog CRUD (admin manages audiences the mobile app picker sees)
    broadcastAudiences: baseUrl + 'admin/broadcast-audiences',
    broadcastAudienceDetail: baseUrl + 'admin/broadcast-audiences',
    createBroadcastAudience: baseUrl + 'admin/broadcast-audiences',
    updateBroadcastAudience: baseUrl + 'admin/broadcast-audiences',
    deleteBroadcastAudience: baseUrl + 'admin/broadcast-audiences',
    // Broadcast moderation — every campaign sent + per-recipient drill-down
    broadcastCampaigns: baseUrl + 'admin/broadcasts',
    broadcastCampaignDetail: baseUrl + 'admin/broadcasts',
    // Broadcast — icon upload + per-tier monthly limit settings
    broadcastAudienceIcon: baseUrl + 'admin/broadcast-audiences/icon',
    broadcastTierLimits: baseUrl + 'admin/broadcast-tier-limits',
    // AI usage — aggregated rollup (feature × month) + paginated raw logs
    aiUsage: baseUrl + 'admin/ai-usage',
    aiUsageLogs: baseUrl + 'admin/ai-usage/logs',
    heldFunds: baseUrl + 'admin/held-funds',
    appleOfferCodes: baseUrl + 'admin/apple-offer-codes',
    refundPreview: baseUrl + 'admin/bookings',
    bookingAudit: baseUrl + 'admin/bookings',
    deactivationReasons: baseUrl + 'admin/deactivation_reasons',
    deactivationReason: baseUrl + 'admin/deactivation_reason',
    deactivateApprovedUser: baseUrl + 'admin/pre-approved-users',
    approvedUserDiscountEligible: baseUrl + 'admin/pre-approved-users',
    rejoinApprovedUser: baseUrl + 'admin/pre-approved-users',
    removeApprovedUserAccess: baseUrl + 'admin/pre-approved-users',
    subscriptionPicker: baseUrl + 'admin/subscription-picker'
}